language: python
python :
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python test/test.py
  - coverage erase
  - coverage run --source=src -m unittest discover -s test/
after_success:
  - coveralls
